graph TD
    classDef fileNode fill:#e1f5fe,stroke:#01579b,stroke-width:2px;
    chapter4_rpy[chapter4.rpy]:::fileNode
    chapter10_rpy[chapter10.rpy]:::fileNode
    chapter22_rpy[chapter22.rpy]:::fileNode
    chapter13_rpy[chapter13.rpy]:::fileNode
    chapter1_rpy[chapter1.rpy]:::fileNode
    chapter15_rpy[chapter15.rpy]:::fileNode
    chapter18_rpy[chapter18.rpy]:::fileNode
    chapter23_rpy[chapter23.rpy]:::fileNode
    chapter9_rpy[chapter9.rpy]:::fileNode
    chapter2_rpy[chapter2.rpy]:::fileNode
    chapter8_rpy[chapter8.rpy]:::fileNode
    chapter16_rpy[chapter16.rpy]:::fileNode
    chapter6_rpy[chapter6.rpy]:::fileNode
    chapter20_rpy[chapter20.rpy]:::fileNode
    chapter3_rpy[chapter3.rpy]:::fileNode
    chapter24_rpy[chapter24.rpy]:::fileNode
    chapter7_rpy[chapter7.rpy]:::fileNode
    chapter17_rpy[chapter17.rpy]:::fileNode
    script_rpy[script.rpy]:::fileNode
    chapter19_rpy[chapter19.rpy]:::fileNode
    chapter5_rpy[chapter5.rpy]:::fileNode
    chapter11_rpy[chapter11.rpy]:::fileNode
    chapter14_rpy[chapter14.rpy]:::fileNode
    chapter12_rpy[chapter12.rpy]:::fileNode
    chapter21_rpy[chapter21.rpy]:::fileNode
    chapter1_rpy --> chapter2_rpy
    chapter10_rpy --> chapter11_rpy
    chapter13_rpy -->|Escalate with l..| chapter14_rpy
    chapter13_rpy -->|File for injunc..| chapter15_rpy
    chapter13_rpy -->|Accept mediated..| chapter7_rpy
    chapter14_rpy --> chapter18_rpy
    chapter15_rpy -->|Funnel more res..| chapter17_rpy
    chapter15_rpy -->|Seek a negotiat..| chapter8_rpy
    chapter16_rpy --> chapter19_rpy
    chapter17_rpy --> chapter21_rpy
    chapter18_rpy --> chapter20_rpy
    chapter19_rpy --> chapter22_rpy
    chapter2_rpy --> chapter3_rpy
    chapter20_rpy --> chapter24_rpy
    chapter21_rpy --> chapter23_rpy
    chapter3_rpy -->|Support Elias' ..| chapter4_rpy
    chapter3_rpy -->|Meet privately ..| chapter9_rpy
    chapter3_rpy -->|Organize an imm..| chapter13_rpy
    chapter4_rpy -->|Negotiate a sca..| chapter5_rpy
    chapter4_rpy -->|Keep expansion .. / Push for immedi..| chapter6_rpy
    chapter9_rpy -->|Accept terms to..| chapter10_rpy
    chapter9_rpy -->|Refuse and dema..| chapter12_rpy
    chapter9_rpy -->|Leak the contra..| chapter16_rpy
    script_rpy --> chapter1_rpy
