graph TD
    classDef fileNode fill:#e1f5fe,stroke:#01579b,stroke-width:2px;
    chapter9_rpy[chapter9.rpy]:::fileNode
    chapter1_rpy[chapter1.rpy]:::fileNode
    chapter18_rpy[chapter18.rpy]:::fileNode
    chapter11_rpy[chapter11.rpy]:::fileNode
    chapter13_rpy[chapter13.rpy]:::fileNode
    chapter12_rpy[chapter12.rpy]:::fileNode
    chapter15_rpy[chapter15.rpy]:::fileNode
    chapter7_rpy[chapter7.rpy]:::fileNode
    chapter5_rpy[chapter5.rpy]:::fileNode
    chapter14_rpy[chapter14.rpy]:::fileNode
    chapter10_rpy[chapter10.rpy]:::fileNode
    chapter6_rpy[chapter6.rpy]:::fileNode
    chapter3_rpy[chapter3.rpy]:::fileNode
    chapter4_rpy[chapter4.rpy]:::fileNode
    chapter8_rpy[chapter8.rpy]:::fileNode
    chapter17_rpy[chapter17.rpy]:::fileNode
    chapter16_rpy[chapter16.rpy]:::fileNode
    chapter2_rpy[chapter2.rpy]:::fileNode
    script_rpy[script.rpy]:::fileNode
    chapter1_rpy --> chapter2_rpy
    chapter10_rpy --> chapter11_rpy
    chapter11_rpy -->|Appeal to Mayor..| chapter12_rpy
    chapter11_rpy -->|Apply for emerg..| chapter18_rpy
    chapter11_rpy -->|Refuse to negot..| chapter16_rpy
    chapter2_rpy --> chapter3_rpy
    chapter3_rpy -->|Negotiate; seek..| chapter4_rpy
    chapter3_rpy -->|Lead a legal an..| chapter7_rpy
    chapter3_rpy -->|Prioritize fast..| chapter10_rpy
    chapter4_rpy --> chapter5_rpy
    chapter5_rpy -->|Accept Cass’s l..| chapter6_rpy
    chapter5_rpy -->|Demand a public..| chapter14_rpy
    chapter5_rpy -->|Refuse to legal..| chapter15_rpy
    chapter7_rpy --> chapter8_rpy
    chapter8_rpy -->|Appeal and inte..| chapter9_rpy
    chapter8_rpy -->|Organize emerge..| chapter17_rpy
    chapter8_rpy -->|Agree to mediat..| chapter13_rpy
    script_rpy --> chapter1_rpy
