graph TD
    classDef fileNode fill:#e1f5fe,stroke:#01579b,stroke-width:2px;
    chapter14_rpy[chapter14.rpy]:::fileNode
    script_rpy[script.rpy]:::fileNode
    chapter13_rpy[chapter13.rpy]:::fileNode
    chapter5_rpy[chapter5.rpy]:::fileNode
    chapter4_rpy[chapter4.rpy]:::fileNode
    chapter12_rpy[chapter12.rpy]:::fileNode
    chapter6_rpy[chapter6.rpy]:::fileNode
    chapter16_rpy[chapter16.rpy]:::fileNode
    chapter18_rpy[chapter18.rpy]:::fileNode
    chapter1_rpy[chapter1.rpy]:::fileNode
    chapter11_rpy[chapter11.rpy]:::fileNode
    chapter7_rpy[chapter7.rpy]:::fileNode
    chapter8_rpy[chapter8.rpy]:::fileNode
    chapter10_rpy[chapter10.rpy]:::fileNode
    chapter9_rpy[chapter9.rpy]:::fileNode
    chapter2_rpy[chapter2.rpy]:::fileNode
    chapter3_rpy[chapter3.rpy]:::fileNode
    chapter1_rpy --> chapter2_rpy
    chapter11_rpy --> chapter12_rpy
    chapter12_rpy -->|Certify and pub.. / Release the raw..| chapter13_rpy
    chapter12_rpy -->|Delay publicati..| chapter18_rpy
    chapter14_rpy -->|Use the recordi..| chapter16_rpy
    chapter14_rpy -->|Destroy the rec..| chapter9_rpy
    chapter2_rpy --> chapter3_rpy
    chapter3_rpy -->|Stand with Rin ..| chapter4_rpy
    chapter3_rpy -->|Meet Elias priv..| chapter7_rpy
    chapter3_rpy -->|Accept a time-l..| chapter11_rpy
    chapter4_rpy --> chapter5_rpy
    chapter5_rpy --> chapter6_rpy
    chapter7_rpy -->|Work with Elias.. / Refuse the priv..| chapter8_rpy
    chapter7_rpy -->|Secretly record..| chapter14_rpy
    chapter8_rpy --> chapter10_rpy
    script_rpy --> chapter1_rpy
