graph TD
    classDef fileNode fill:#e1f5fe,stroke:#01579b,stroke-width:2px;
    chapter12_rpy[chapter12.rpy]:::fileNode
    chapter18_rpy[chapter18.rpy]:::fileNode
    chapter2_rpy[chapter2.rpy]:::fileNode
    chapter15_rpy[chapter15.rpy]:::fileNode
    chapter6_rpy[chapter6.rpy]:::fileNode
    chapter17_rpy[chapter17.rpy]:::fileNode
    chapter3_rpy[chapter3.rpy]:::fileNode
    chapter1_rpy[chapter1.rpy]:::fileNode
    chapter14_rpy[chapter14.rpy]:::fileNode
    chapter10_rpy[chapter10.rpy]:::fileNode
    script_rpy[script.rpy]:::fileNode
    chapter16_rpy[chapter16.rpy]:::fileNode
    chapter5_rpy[chapter5.rpy]:::fileNode
    chapter4_rpy[chapter4.rpy]:::fileNode
    chapter8_rpy[chapter8.rpy]:::fileNode
    chapter9_rpy[chapter9.rpy]:::fileNode
    chapter13_rpy[chapter13.rpy]:::fileNode
    chapter11_rpy[chapter11.rpy]:::fileNode
    chapter7_rpy[chapter7.rpy]:::fileNode
    chapter1_rpy --> chapter2_rpy
    chapter12_rpy -->|Negotiate a for..| chapter13_rpy
    chapter12_rpy -->|Accept corporat..| chapter15_rpy
    chapter12_rpy -->|Refuse the firm..| chapter16_rpy
    chapter13_rpy --> chapter14_rpy
    chapter15_rpy --> chapter18_rpy
    chapter16_rpy --> chapter17_rpy
    chapter2_rpy --> chapter3_rpy
    chapter3_rpy -->|Invite a commun..| chapter4_rpy
    chapter3_rpy -->|Recommend Mateo..| chapter8_rpy
    chapter3_rpy -->|Open the pilot ..| chapter12_rpy
    chapter4_rpy -->|Accept Mateo's ..| chapter5_rpy
    chapter4_rpy -->|Refuse municipa.. / Coordinate a pr..| chapter6_rpy
    chapter5_rpy --> chapter7_rpy
    chapter8_rpy -->|Fully cooperate..| chapter9_rpy
    chapter8_rpy -->|Coordinate a pu.. / Secretly negoti..| chapter11_rpy
    chapter9_rpy --> chapter10_rpy
    script_rpy --> chapter1_rpy
