graph TD
    classDef fileNode fill:#e1f5fe,stroke:#01579b,stroke-width:2px;
    chapter14_rpy[chapter14.rpy]:::fileNode
    chapter20_rpy[chapter20.rpy]:::fileNode
    chapter13_rpy[chapter13.rpy]:::fileNode
    chapter5_rpy[chapter5.rpy]:::fileNode
    chapter31_rpy[chapter31.rpy]:::fileNode
    chapter33_rpy[chapter33.rpy]:::fileNode
    script_rpy[script.rpy]:::fileNode
    chapter28_rpy[chapter28.rpy]:::fileNode
    chapter19_rpy[chapter19.rpy]:::fileNode
    chapter24_rpy[chapter24.rpy]:::fileNode
    chapter22_rpy[chapter22.rpy]:::fileNode
    chapter1_rpy[chapter1.rpy]:::fileNode
    chapter10_rpy[chapter10.rpy]:::fileNode
    chapter7_rpy[chapter7.rpy]:::fileNode
    chapter8_rpy[chapter8.rpy]:::fileNode
    chapter17_rpy[chapter17.rpy]:::fileNode
    chapter26_rpy[chapter26.rpy]:::fileNode
    chapter2_rpy[chapter2.rpy]:::fileNode
    chapter1_rpy --> chapter2_rpy
    chapter13_rpy --> chapter14_rpy
    chapter14_rpy -->|Push the leak a..| chapter17_rpy
    chapter14_rpy -->|Accept a watere..| chapter24_rpy
    chapter14_rpy -->|Walk away and d..| chapter33_rpy
    chapter19_rpy --> chapter20_rpy
    chapter2_rpy -->|Organize the co..| chapter5_rpy
    chapter2_rpy -->|Enter mediated ..| chapter13_rpy
    chapter2_rpy -->|Build a data-dr..| chapter19_rpy
    chapter20_rpy -->|Launch a coordi..| chapter22_rpy
    chapter20_rpy -->|Proceed quietly..| chapter8_rpy
    chapter20_rpy -->|Negotiate a con..| chapter26_rpy
    chapter5_rpy --> chapter7_rpy
    chapter7_rpy -->|Escalate: organ..| chapter10_rpy
    chapter7_rpy -->|Switch to legal..| chapter28_rpy
    chapter7_rpy -->|Return to the t..| chapter31_rpy
    script_rpy --> chapter1_rpy
