graph TD
    classDef fileNode fill:#e1f5fe,stroke:#01579b,stroke-width:2px;
    chapter37_rpy[chapter37.rpy]:::fileNode
    chapter22_rpy[chapter22.rpy]:::fileNode
    chapter18_rpy[chapter18.rpy]:::fileNode
    script_rpy[script.rpy]:::fileNode
    chapter15_rpy[chapter15.rpy]:::fileNode
    chapter47_rpy[chapter47.rpy]:::fileNode
    chapter23_rpy[chapter23.rpy]:::fileNode
    chapter2_rpy[chapter2.rpy]:::fileNode
    chapter36_rpy[chapter36.rpy]:::fileNode
    chapter19_rpy[chapter19.rpy]:::fileNode
    chapter31_rpy[chapter31.rpy]:::fileNode
    chapter34_rpy[chapter34.rpy]:::fileNode
    chapter39_rpy[chapter39.rpy]:::fileNode
    chapter33_rpy[chapter33.rpy]:::fileNode
    chapter21_rpy[chapter21.rpy]:::fileNode
    chapter20_rpy[chapter20.rpy]:::fileNode
    chapter42_rpy[chapter42.rpy]:::fileNode
    chapter12_rpy[chapter12.rpy]:::fileNode
    chapter44_rpy[chapter44.rpy]:::fileNode
    chapter29_rpy[chapter29.rpy]:::fileNode
    chapter51_rpy[chapter51.rpy]:::fileNode
    chapter40_rpy[chapter40.rpy]:::fileNode
    chapter4_rpy[chapter4.rpy]:::fileNode
    chapter24_rpy[chapter24.rpy]:::fileNode
    chapter46_rpy[chapter46.rpy]:::fileNode
    chapter17_rpy[chapter17.rpy]:::fileNode
    chapter27_rpy[chapter27.rpy]:::fileNode
    chapter3_rpy[chapter3.rpy]:::fileNode
    chapter50_rpy[chapter50.rpy]:::fileNode
    chapter53_rpy[chapter53.rpy]:::fileNode
    chapter45_rpy[chapter45.rpy]:::fileNode
    chapter30_rpy[chapter30.rpy]:::fileNode
    chapter25_rpy[chapter25.rpy]:::fileNode
    chapter28_rpy[chapter28.rpy]:::fileNode
    chapter52_rpy[chapter52.rpy]:::fileNode
    chapter48_rpy[chapter48.rpy]:::fileNode
    chapter41_rpy[chapter41.rpy]:::fileNode
    chapter13_rpy[chapter13.rpy]:::fileNode
    chapter7_rpy[chapter7.rpy]:::fileNode
    chapter49_rpy[chapter49.rpy]:::fileNode
    chapter11_rpy[chapter11.rpy]:::fileNode
    chapter35_rpy[chapter35.rpy]:::fileNode
    chapter16_rpy[chapter16.rpy]:::fileNode
    chapter14_rpy[chapter14.rpy]:::fileNode
    chapter5_rpy[chapter5.rpy]:::fileNode
    chapter32_rpy[chapter32.rpy]:::fileNode
    chapter26_rpy[chapter26.rpy]:::fileNode
    chapter38_rpy[chapter38.rpy]:::fileNode
    chapter6_rpy[chapter6.rpy]:::fileNode
    chapter8_rpy[chapter8.rpy]:::fileNode
    chapter9_rpy[chapter9.rpy]:::fileNode
    chapter1_rpy[chapter1.rpy]:::fileNode
    chapter43_rpy[chapter43.rpy]:::fileNode
    chapter10_rpy[chapter10.rpy]:::fileNode
    chapter1_rpy --> chapter2_rpy
    chapter10_rpy -->|Force a public ..| chapter12_rpy
    chapter10_rpy -->|Trust Elias and..| chapter22_rpy
    chapter10_rpy -->|Accept Kai's co..| chapter29_rpy
    chapter11_rpy --> chapter14_rpy
    chapter12_rpy --> chapter15_rpy
    chapter13_rpy --> chapter18_rpy
    chapter14_rpy --> chapter16_rpy
    chapter15_rpy --> chapter17_rpy
    chapter16_rpy -->|Accept Kai’s fa..| chapter19_rpy
    chapter16_rpy -->|Push for an exp..| chapter31_rpy
    chapter16_rpy -->|Withdraw and de..| chapter41_rpy
    chapter17_rpy -->|Accept Kai’s fa..| chapter21_rpy
    chapter17_rpy -->|Push for an exp..| chapter36_rpy
    chapter17_rpy -->|Withdraw and de..| chapter42_rpy
    chapter18_rpy -->|Accept Kai’s fa..| chapter23_rpy
    chapter18_rpy -->|Push for an exp..| chapter40_rpy
    chapter18_rpy -->|Withdraw and de..| chapter43_rpy
    chapter19_rpy --> chapter25_rpy
    chapter2_rpy --> chapter3_rpy
    chapter20_rpy --> chapter27_rpy
    chapter21_rpy --> chapter26_rpy
    chapter22_rpy --> chapter30_rpy
    chapter23_rpy --> chapter28_rpy
    chapter24_rpy --> chapter38_rpy
    chapter25_rpy --> chapter35_rpy
    chapter26_rpy --> chapter33_rpy
    chapter27_rpy --> chapter32_rpy
    chapter28_rpy --> chapter34_rpy
    chapter29_rpy --> chapter37_rpy
    chapter3_rpy -->|Push the neighb..| chapter4_rpy
    chapter3_rpy -->|Work through El..| chapter7_rpy
    chapter3_rpy -->|Meet Kai privat..| chapter13_rpy
    chapter30_rpy --> chapter39_rpy
    chapter31_rpy --> chapter45_rpy
    chapter32_rpy --> chapter47_rpy
    chapter33_rpy --> chapter50_rpy
    chapter34_rpy --> chapter49_rpy
    chapter35_rpy --> chapter52_rpy
    chapter36_rpy --> chapter53_rpy
    chapter37_rpy --> chapter44_rpy
    chapter38_rpy --> chapter48_rpy
    chapter39_rpy --> chapter51_rpy
    chapter4_rpy --> chapter5_rpy
    chapter40_rpy --> chapter46_rpy
    chapter5_rpy --> chapter6_rpy
    chapter6_rpy --> chapter8_rpy
    chapter7_rpy --> chapter9_rpy
    chapter8_rpy --> chapter10_rpy
    chapter9_rpy -->|Force a public ..| chapter11_rpy
    chapter9_rpy -->|Trust Elias and..| chapter20_rpy
    chapter9_rpy -->|Accept Kai's co..| chapter24_rpy
    script_rpy --> chapter1_rpy
