graph TD
    classDef fileNode fill:#e1f5fe,stroke:#01579b,stroke-width:2px;
    chapter12_rpy[chapter12.rpy]:::fileNode
    chapter3_rpy[chapter3.rpy]:::fileNode
    chapter2_rpy[chapter2.rpy]:::fileNode
    chapter1_rpy[chapter1.rpy]:::fileNode
    chapter4_rpy[chapter4.rpy]:::fileNode
    chapter14_rpy[chapter14.rpy]:::fileNode
    chapter8_rpy[chapter8.rpy]:::fileNode
    chapter10_rpy[chapter10.rpy]:::fileNode
    chapter15_rpy[chapter15.rpy]:::fileNode
    chapter7_rpy[chapter7.rpy]:::fileNode
    script_rpy[script.rpy]:::fileNode
    chapter6_rpy[chapter6.rpy]:::fileNode
    chapter9_rpy[chapter9.rpy]:::fileNode
    chapter13_rpy[chapter13.rpy]:::fileNode
    chapter11_rpy[chapter11.rpy]:::fileNode
    chapter5_rpy[chapter5.rpy]:::fileNode
    chapter1_rpy --> chapter2_rpy
    chapter10_rpy --> chapter11_rpy
    chapter11_rpy -->|Lead the agency..| chapter12_rpy
    chapter11_rpy -->|Refuse the agen..| chapter13_rpy
    chapter11_rpy -->|Negotiate a con..| chapter14_rpy
    chapter2_rpy --> chapter3_rpy
    chapter3_rpy -->|Side with Kaito.. / Attempt to brok..| chapter4_rpy
    chapter3_rpy -->|Align with Elen..| chapter10_rpy
    chapter4_rpy -->|Lead an experim..| chapter5_rpy
    chapter4_rpy -->|Accept a limite..| chapter6_rpy
    chapter4_rpy -->|Step back and l..| chapter8_rpy
    chapter5_rpy -->|Double down on ..| chapter7_rpy
    chapter5_rpy -->|Accept conditio..| chapter9_rpy
    chapter5_rpy -->|Propose a feder..| chapter15_rpy
    script_rpy --> chapter1_rpy
