graph TD
    classDef fileNode fill:#e1f5fe,stroke:#01579b,stroke-width:2px;
    chapter2_rpy[chapter2.rpy]:::fileNode
    chapter8_rpy[chapter8.rpy]:::fileNode
    chapter10_rpy[chapter10.rpy]:::fileNode
    chapter5_rpy[chapter5.rpy]:::fileNode
    chapter15_rpy[chapter15.rpy]:::fileNode
    script_rpy[script.rpy]:::fileNode
    chapter1_rpy[chapter1.rpy]:::fileNode
    chapter4_rpy[chapter4.rpy]:::fileNode
    chapter6_rpy[chapter6.rpy]:::fileNode
    chapter7_rpy[chapter7.rpy]:::fileNode
    chapter13_rpy[chapter13.rpy]:::fileNode
    chapter11_rpy[chapter11.rpy]:::fileNode
    chapter14_rpy[chapter14.rpy]:::fileNode
    chapter12_rpy[chapter12.rpy]:::fileNode
    chapter3_rpy[chapter3.rpy]:::fileNode
    chapter9_rpy[chapter9.rpy]:::fileNode
    chapter1_rpy --> chapter2_rpy
    chapter12_rpy -->|Hold the line p..| chapter13_rpy
    chapter12_rpy -->|Call for immedi.. / Invite Elias to..| chapter14_rpy
    chapter13_rpy --> chapter15_rpy
    chapter2_rpy --> chapter3_rpy
    chapter3_rpy -->|Negotiate with ..| chapter4_rpy
    chapter3_rpy -->|Publicly confro..| chapter8_rpy
    chapter3_rpy -->|Organize direct..| chapter12_rpy
    chapter4_rpy -->|Insist Elias ta..| chapter5_rpy
    chapter4_rpy -->|Accept a compro.. / Delay and bring..| chapter6_rpy
    chapter5_rpy --> chapter7_rpy
    chapter8_rpy -->|Push for immedi..| chapter9_rpy
    chapter8_rpy -->|Double down on .. / Negotiate a pub..| chapter11_rpy
    chapter9_rpy --> chapter10_rpy
    script_rpy --> chapter1_rpy
