graph TD
    classDef fileNode fill:#e1f5fe,stroke:#01579b,stroke-width:2px;
    chapter33_rpy[chapter33.rpy]:::fileNode
    chapter30_rpy[chapter30.rpy]:::fileNode
    chapter27_rpy[chapter27.rpy]:::fileNode
    chapter13_rpy[chapter13.rpy]:::fileNode
    chapter18_rpy[chapter18.rpy]:::fileNode
    chapter17_rpy[chapter17.rpy]:::fileNode
    chapter19_rpy[chapter19.rpy]:::fileNode
    chapter24_rpy[chapter24.rpy]:::fileNode
    chapter31_rpy[chapter31.rpy]:::fileNode
    chapter28_rpy[chapter28.rpy]:::fileNode
    chapter3_rpy[chapter3.rpy]:::fileNode
    chapter25_rpy[chapter25.rpy]:::fileNode
    chapter8_rpy[chapter8.rpy]:::fileNode
    chapter32_rpy[chapter32.rpy]:::fileNode
    chapter10_rpy[chapter10.rpy]:::fileNode
    chapter21_rpy[chapter21.rpy]:::fileNode
    chapter2_rpy[chapter2.rpy]:::fileNode
    chapter1_rpy[chapter1.rpy]:::fileNode
    chapter22_rpy[chapter22.rpy]:::fileNode
    chapter29_rpy[chapter29.rpy]:::fileNode
    chapter11_rpy[chapter11.rpy]:::fileNode
    chapter5_rpy[chapter5.rpy]:::fileNode
    chapter20_rpy[chapter20.rpy]:::fileNode
    chapter6_rpy[chapter6.rpy]:::fileNode
    chapter14_rpy[chapter14.rpy]:::fileNode
    chapter15_rpy[chapter15.rpy]:::fileNode
    chapter12_rpy[chapter12.rpy]:::fileNode
    chapter9_rpy[chapter9.rpy]:::fileNode
    chapter4_rpy[chapter4.rpy]:::fileNode
    script_rpy[script.rpy]:::fileNode
    chapter16_rpy[chapter16.rpy]:::fileNode
    chapter26_rpy[chapter26.rpy]:::fileNode
    chapter23_rpy[chapter23.rpy]:::fileNode
    chapter7_rpy[chapter7.rpy]:::fileNode
    chapter1_rpy --> chapter2_rpy
    chapter10_rpy --> chapter12_rpy
    chapter11_rpy --> chapter14_rpy
    chapter12_rpy --> chapter15_rpy
    chapter13_rpy --> chapter18_rpy
    chapter14_rpy --> chapter16_rpy
    chapter15_rpy --> chapter17_rpy
    chapter16_rpy -->|Work with Lila .. / Mobilize the co..| chapter19_rpy
    chapter16_rpy -->|Expose the leak..| chapter28_rpy
    chapter17_rpy -->|Work with Lila .. / Mobilize the co..| chapter20_rpy
    chapter17_rpy -->|Expose the leak..| chapter29_rpy
    chapter18_rpy -->|Work with Lila .. / Mobilize the co..| chapter21_rpy
    chapter18_rpy -->|Expose the leak..| chapter30_rpy
    chapter19_rpy --> chapter22_rpy
    chapter2_rpy --> chapter3_rpy
    chapter20_rpy --> chapter23_rpy
    chapter21_rpy --> chapter24_rpy
    chapter22_rpy --> chapter27_rpy
    chapter23_rpy --> chapter25_rpy
    chapter24_rpy --> chapter26_rpy
    chapter25_rpy --> chapter32_rpy
    chapter26_rpy --> chapter31_rpy
    chapter27_rpy --> chapter33_rpy
    chapter3_rpy -->|Push the hybrid..| chapter4_rpy
    chapter3_rpy -->|Openly propose ..| chapter7_rpy
    chapter3_rpy -->|Call for a priv..| chapter13_rpy
    chapter4_rpy --> chapter5_rpy
    chapter5_rpy --> chapter6_rpy
    chapter6_rpy --> chapter8_rpy
    chapter7_rpy --> chapter9_rpy
    chapter8_rpy --> chapter10_rpy
    chapter9_rpy --> chapter11_rpy
    script_rpy --> chapter1_rpy
