graph TD
    classDef fileNode fill:#e1f5fe,stroke:#01579b,stroke-width:2px;
    chapter18_rpy[chapter18.rpy]:::fileNode
    chapter13_rpy[chapter13.rpy]:::fileNode
    chapter19_rpy[chapter19.rpy]:::fileNode
    chapter17_rpy[chapter17.rpy]:::fileNode
    chapter24_rpy[chapter24.rpy]:::fileNode
    chapter3_rpy[chapter3.rpy]:::fileNode
    chapter25_rpy[chapter25.rpy]:::fileNode
    chapter8_rpy[chapter8.rpy]:::fileNode
    chapter10_rpy[chapter10.rpy]:::fileNode
    chapter21_rpy[chapter21.rpy]:::fileNode
    chapter2_rpy[chapter2.rpy]:::fileNode
    chapter1_rpy[chapter1.rpy]:::fileNode
    chapter22_rpy[chapter22.rpy]:::fileNode
    chapter11_rpy[chapter11.rpy]:::fileNode
    chapter5_rpy[chapter5.rpy]:::fileNode
    chapter20_rpy[chapter20.rpy]:::fileNode
    chapter6_rpy[chapter6.rpy]:::fileNode
    chapter14_rpy[chapter14.rpy]:::fileNode
    chapter15_rpy[chapter15.rpy]:::fileNode
    chapter12_rpy[chapter12.rpy]:::fileNode
    chapter9_rpy[chapter9.rpy]:::fileNode
    chapter4_rpy[chapter4.rpy]:::fileNode
    script_rpy[script.rpy]:::fileNode
    chapter16_rpy[chapter16.rpy]:::fileNode
    chapter26_rpy[chapter26.rpy]:::fileNode
    chapter23_rpy[chapter23.rpy]:::fileNode
    chapter7_rpy[chapter7.rpy]:::fileNode
    chapter1_rpy --> chapter2_rpy
    chapter10_rpy -->|Show raw, unedi..| chapter12_rpy
    chapter10_rpy -->|Focus on specta..| chapter14_rpy
    chapter10_rpy -->|Invite Elias to..| chapter15_rpy
    chapter11_rpy --> chapter18_rpy
    chapter12_rpy --> chapter19_rpy
    chapter13_rpy --> chapter23_rpy
    chapter14_rpy --> chapter26_rpy
    chapter15_rpy --> chapter17_rpy
    chapter16_rpy --> chapter25_rpy
    chapter17_rpy --> chapter22_rpy
    chapter18_rpy --> chapter24_rpy
    chapter19_rpy --> chapter20_rpy
    chapter2_rpy --> chapter3_rpy
    chapter3_rpy -->|Lead the commun..| chapter4_rpy
    chapter3_rpy -->|Work with Elias..| chapter7_rpy
    chapter3_rpy -->|Stage a high-pr..| chapter10_rpy
    chapter4_rpy --> chapter5_rpy
    chapter5_rpy -->|We escalate — m..| chapter6_rpy
    chapter5_rpy -->|Protect our exp..| chapter16_rpy
    chapter5_rpy -->|Negotiate a sho..| chapter21_rpy
    chapter7_rpy --> chapter8_rpy
    chapter8_rpy -->|Release the pro..| chapter9_rpy
    chapter8_rpy -->|Keep them confi..| chapter11_rpy
    chapter8_rpy -->|Do a field demo..| chapter13_rpy
    script_rpy --> chapter1_rpy
