graph TD
    classDef fileNode fill:#e1f5fe,stroke:#01579b,stroke-width:2px;
    chapter6_rpy[chapter6.rpy]:::fileNode
    chapter9_rpy[chapter9.rpy]:::fileNode
    script_rpy[script.rpy]:::fileNode
    chapter4_rpy[chapter4.rpy]:::fileNode
    chapter2_rpy[chapter2.rpy]:::fileNode
    chapter3_rpy[chapter3.rpy]:::fileNode
    chapter1_rpy[chapter1.rpy]:::fileNode
    chapter13_rpy[chapter13.rpy]:::fileNode
    chapter10_rpy[chapter10.rpy]:::fileNode
    chapter15_rpy[chapter15.rpy]:::fileNode
    chapter5_rpy[chapter5.rpy]:::fileNode
    chapter8_rpy[chapter8.rpy]:::fileNode
    chapter14_rpy[chapter14.rpy]:::fileNode
    chapter11_rpy[chapter11.rpy]:::fileNode
    chapter7_rpy[chapter7.rpy]:::fileNode
    chapter12_rpy[chapter12.rpy]:::fileNode
    chapter1_rpy --> chapter2_rpy
    chapter10_rpy --> chapter11_rpy
    chapter11_rpy -->|Build long-term.. / Prioritize imme..| chapter12_rpy
    chapter11_rpy -->|Step back sligh..| chapter15_rpy
    chapter2_rpy --> chapter3_rpy
    chapter3_rpy -->|Take Sienna's o..| chapter4_rpy
    chapter3_rpy -->|Lead a communit..| chapter7_rpy
    chapter3_rpy -->|Scale decentral..| chapter10_rpy
    chapter4_rpy --> chapter5_rpy
    chapter5_rpy -->|Push for commun.. / Prioritize tech..| chapter6_rpy
    chapter5_rpy -->|Refuse the comp..| chapter13_rpy
    chapter7_rpy --> chapter8_rpy
    chapter8_rpy -->|Interrupt the c.. / Publicly releas..| chapter9_rpy
    chapter8_rpy -->|Build a scalabl..| chapter14_rpy
    script_rpy --> chapter1_rpy
